### ISSUE TITLE
What is the license model?

### ISSUE THREAD

**Issue by tinysun212** [YajS/NikPEViewer#1]
There are no license files in this repository.
I just forked this. May I change this code and open to others?
How about adding a GPL or BSD, Apache open source license file?

**Comment by YajS** [comment]
This was a hobby project, I don't believe in license and feel free to use this code for commercial or non commercial. I do have some plan to update this code in future. What changes you have in mind?

**Comment by tinysun212** [comment]
Thanks for your nice tool.
I just wanted to change the code and share it with everyone. I think I should not touch your code.

**Comment by harryisgamer** [comment]
@YajS You should probably add a license so people can use your code. If you just want to let people use your code no matter what (no obligations) you should probably use the [Unlicense](https://unlicense.org/). This makes the code public domain. If you want people to give you credit, you should probably use the MIT license. For more information on choosing a license, [choosealicense.com](https://choosealicense.com/) is a good resource.

**Comment by YajS** [comment]
Thanks, 
"License" text has now been added to the Project Readme file.

**Comment by tinysun212** [comment]
Thanks for the public domain license selection.
